linters:
  enable:
    - deadcode
    - errcheck
    - ineffassign
    - structcheck
    - typecheck
    - varcheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - interfacer
    - maligned
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - govet
    - gocognit
