linters:
  enable:
    - errcheck
    - ineffassign
    - unused
    - typecheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - govet
    - gocognit
    - dupword
    - errorlint
    - godot
    - gofumpt
    - nolintlint
    - nosprintfhostport
    - tenv
    - thelper
    - wrapcheck
